### ISSUE TITLE
RSS podcast source provider

### ISSUE THREAD

**Issue by triandco** [triandco/local-index-prototype#7]
Implement a file [source provider](https://github.com/triandco/local-index-prototype/blob/main/docs/pipeline.md#sourcing) which watches a rss feed and generates a document for each file.

### Context
RSS feed are a format to provide readable update to subscribers both human and aggregator. It is commonly used by media publisher, blog, and podcaster.

Base schema: https://validator.w3.org/feed/docs/rss2.html
Common namespace extensions: 
  - [dublinCore](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/): ```http://purl.org/dc/elements/1.1/``` often seen in news RSS
  - [Yahoo media tags](https://www.rssboard.org/media-rss): ```http://search.yahoo.com/mrss/``` often seen in RSS of media publisher
  - [Itune podcast](http://www.itunes.com/dtds/podcast-1.0.dtd): ```http://www.itunes.com/dtds/podcast-1.0.dtd``` commonly seen in podcast RSS of apple, google, and spotify
  - [Spotify](https://support.spotifyforpodcasters.com/hc/en-us/articles/360044440991-Podcast-specification-doc): ```https://www.spotify.com/au/ns/rss/``` Spotify specific namespace
  - [Podlove](https://podlove.org/): ```https://podlove.org/simple-chapters/``` specific namespace which Spotify also support

Podcaster commonly use ```<enclosure>``` tag (part of RSS standard from v0.92) to include a link to audio of the podcast.
  
A feed contains updates from the publisher at a time and might get updated frequently. The content of the feed is entirely up to the publisher, thus there could be a mix of old and news item, there is no constraint on what is available in a feed.

### Acceptance Criteria
An RSS source provider should
1. RSS URL can be provide to application via code (hard-coded)
1. When feed is updated with new item, new item is added
1. When feed is updated with existing item, existing item is updated
1. When application stop and restarted, if there is a new feed, items are added accordingly

**Comment by NickDarvey** [comment]
>Common namespace extensions: [...]

Maybe we should make this issue about podcasts specifically then instead of RSS in general. That way, we can specialize this provider to use all these extensions and fetch all the podcast-related things we want to archive and index. (We should probably just start with the base schema still, to build this incrementally.)

>Podcaster commonly use tag (part of RSS standard from v0.92) to include a link to audio of the podcast.

Which tag?

> 3. When feed is updated with existing item, existing item is left unchanged

Is this just out-of-scope for this first iteration of the source provider?
(I think we'll eventually need it. For example, when a publisher publishes an incorrect link to the audio of the podcast, then later updates the item with the correct link, we'd want to use the updated item.)

**Comment by triandco** [comment]
I agree, let's specialise this for podcast specifically.

I updated to show the tag ```<enclosure/>```

Number 3 should be in scope. I believe we can easily match an item of the podcast by a combination of its ```<link/>```, ```<pubDate>```, and ```<enclosure/>```
